/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CountryDto { 
    id?: number;
    name?: string;
    iso2?: string;
    iso3?: string;
    numericCode?: number;
    phoneCode?: number;
    capitalName?: string;
    currency?: string;
    currencyName?: string;
    currencySymbol?: string;
    tld?: string;
    nativeName?: string;
    region?: string;
    regionId?: number;
    subregion?: string;
    subregionId?: number;
    nationality?: string;
    timezones?: string;
    latitude?: number;
    longitude?: number;
    emoji?: string;
    emojiU?: string;
}

