/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface CountryTableDto {
  id?: number;
  name?: string;
  iso3?: string;
  numericCode?: number;
  capitalName?: string;
  currency?: string;
  region?: string;
  subregion?: string;
  latitudeLongitude?: string;
  emoji?: string;
}
